// <auto-generated />
namespace TrackingModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tracking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tracking));
        
        string IMigrationMetadata.Id
        {
            get { return "202103072049108_tracking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
